### ISSUE TITLE
Older version of minio 6.0.2 to 7.0.1 to improvement request

### ISSUE THREAD

**Issue by bhuiyanmobasshir94** [py-pa/django-minio-storage#112]
Specifically, on 7.0.1 I really found a considerable amount of changes in file names, like `SessConfig`, `Rule` classes have been defined separately in a particular module. Besides, I saw `ImportError` for `get_base_url()` function with newer function. I couldn't work with encryption on our production-level project for this incompatibility.

**Comment by thomasf** [comment]
This is a slightly annoying change in the minio client that they change so much when they probably could have made backwards compatible change for most of it. Now there will be people who depend on the old or the new version of the client library but since both versions of the client has the same import path they can not coexist inside a django project.

*sigh*

I will not spend any time on upgrading the client in here in the foreseeable future because I don't event want to upgrade to v7 in my companys projects at all right now but I will review a pull request if someone else does it.

**Comment by thomasf** [comment]
Since stuff like exceptions has been totally changed it is probably easy to introduce subtle behavioral changes by mistake at the storage/file class level. We probably don't have nearly enough test coverage to properly make that transition without risking new bugs by mistake.

**Comment by bhuiyanmobasshir94** [comment]
@thomasf thanks for your response. I totally understand your point and thanks for the work you have done so far, it really saved my day.

**Comment by thomasf** [comment]
released in v0.5.0
