### ISSUE TITLE
get_target_url no longer exists

### ISSUE THREAD

**Issue by odigity** [py-pa/django-minio-storage#117]
I just noticed that minio_storage/storage.py makes use of `minio.helpers.get_target_url`.

However, it appears that function no longer exists.

https://github.com/minio/minio-py/search?q=get_target_url

**Comment by thomasf** [comment]
https://github.com/py-pa/django-minio-storage/issues/112

Right now I do not personally have the time or need or even want to upgrade this package for my own use since I use the earlier minio-py version in a lot of projects I also don't have time to upgrade. 

I will review a patch doing an upgrade to minio-py 7.
