### ISSUE TITLE
Decide and document how errors/exceptions works in the storage/file classes

### ISSUE THREAD

**Issue by thomasf** [py-pa/django-minio-storage#35]
To what extent should the exceptions be translated to IOError and things which django file handling code might be expecting.

**Comment by Yurmusp** [comment]
There are also ValueError exceptions that are somewhat different. I think it is worth looking how S3 Bota's Storage is done in this respect.

**Comment by Yurmusp** [comment]
Just looked into S3.
They wrap all calls into handlers that repack all underneath exceptions into their own exceptions that they inherit from OSError and/or IOError.
It is defined at the top of the source here:
https://github.com/etianen/django-s3-storage/blob/master/django_s3_storage/storage.py#L26

Also, they use this `@_wrap_errors` attribute  in order to apply default exception handling/repacking to number of functions and this makes code more readable.
I probably would do something similar in minio.

With current code I have issues in my existing project. Minio library throws different exceptions than S3 or FileSystemStorage. In particular when key does not exist in some test that I have, I get ValueError with FileSystem storage and some minio-py error of type that I have no access at caller with minio storage.
In particular it throws exceptions that are declared in minio-py and those are not visible at caller level. I think outside of standard python exceptions (like ValueError, etc.) we shall repack everything else. 
S3 seems repacks everything. 

I also looked into FileSystemStorage implementation.
They internally handle and filter only IOError and OSError, sometimes throw ValueError.

From what I see, I would had ValueError passed through and everything else repack into our own exception inherited from IOError and/or OSError same way as in S3.

@thomasf 
Let me know what you think, because I need to do this for my need one way or another and I would want we agree on the strategy.

**Comment by thomasf** [comment]
I think it's mostly a question about which exceptions should be wrapped in which scenario..

I would like to have obvious misconfiguration related errors such as NoSuchBucket to raised in their original form while error which causes internal django features or widely adopted packages to behave bad probably should be wrapped. 

Having said this I've been using django-minio-storage within a django project which uses a bunch of packages including wagtail and is heavily used for by image uploading/processing and I have yet to see any practical problems because of exceptions.

**Comment by thomasf** [comment]
https://github.com/py-pa/django-minio-storage/pull/40 implemented a basic error type wrapping minio errors
