### ISSUE TITLE
Uncaught Exception - checking if file exists

### ISSUE THREAD

**Issue by mfdeux** [py-pa/django-minio-storage#38]
Packages:
Django==1.11.5
django-minio-storage==0.1.0 (installed from pypi)
minio==2.2.4

When saving file, MinioStorage checks if file exists and is supposed to return false if minio returns NoSuchKey exception.  With packages installed above, this causes uncaught exception in Django and the file is not saved.  The problem is that NoSuchKey is not a ResponseError so checking if error.code == "NoSuchKey" is not working.  Problem can be fixed by importing the except NoSuchKey from minio.error instead.

**Comment by thomasf** [comment]
we have not released a new version with the `django-minio-storage` package name yet.. `django-minio-storage-py-pa==0.0.2` have lots of fixes.  There are some scenarios which still might cause that problem but it's resolved for a bunch of cases. I have that version in production in a wagtail project which uses a lot of images and that works fine.

The reason that we havent released a 0.2.0 yes is that some of the error handling isn't implemented yet and I don't want to change the exception behavior afterwards since it changes the public API again.

**Comment by thomasf** [comment]
maybe fixed by 67e6be7c6d7031f35fd8a4b65a9d58cc8cc2d105
