### ISSUE TITLE
support bucket region

### ISSUE THREAD

**Issue by ArchiFleKs** [py-pa/django-minio-storage#53]
Hi,

Minio API supports region when using a cloud provider that supports if (AWS, GCP), as per: 
https://docs.minio.io/docs/python-client-api-reference#make_bucket

I think it is just a matter of adding a new ENV and pass it to:
https://github.com/py-pa/django-minio-storage/blob/master/minio_storage/storage.py#L57

if it is defined. I can try to do a PR but I'm not really skilled in python.

**Comment by thomasf** [comment]
While the S3 API generally should work with any provider it's probably better to use a AWS or GCP specific storage backend for those platforms.

**Comment by ArchiFleKs** [comment]
Yes it is a possibility but we are using minio to abstract provider, and with minio API and CLI : 

`mc mb mygcs/test-minio-cstb --region europe-west1` where mygcs is a bakend type minio is working to create regional bucket only

**Comment by thomasf** [comment]
Not sure what you mean by ENV but all settings should be defined in `settings.py` for the preset media/staticfiles storage classes, it's up the user to assign it from environment variables if they want to. I use both AWS S3 and Minio servers in the same projects and that would start to fail if the environment variable is parsed so it's an forwards incompatible change which should be avoided if possible.

**Comment by ArchiFleKs** [comment]
I meant as a en environnement variables also. From what I think I
understand from the source code when you call make_bucket you do not pass
any args about the region ?
Le jeu. 1 mars 2018 à 15:00, Thomas Frössman <notifications@github.com> a
écrit :

**Comment by thomasf** [comment]
If the region is all you want to add you need to add it to the following places: 

https://github.com/py-pa/django-minio-storage/blob/master/docs/usage.md

**Comment by thomasf** [comment]
you need to add it to:

- https://github.com/py-pa/django-minio-storage/blob/master/minio_storage/storage.py#L43
- https://github.com/py-pa/django-minio-storage/blob/master/minio_storage/storage.py#L239
- https://github.com/py-pa/django-minio-storage/blob/master/minio_storage/storage.py#L260
- https://github.com/py-pa/django-minio-storage/blob/master/docs/usage.md

and..

- Region settings are used for much more than creating buckets, guess the minio
  client instance should be created with `region="..."` to have it everywhere
  but you really have to read through the code to make sure that everything is
  called correctly with the custom region.

- Don't read environment variables directly, people can rely on
  https://github.com/joke2k/django-environ or do it themselves in settings.py
  if they want environment variable support.

- Add test(s) to verify that minio storage operation fails when used with the
  wrong region.

- Don't mention support for anything but Minio in the code/docs since it's not
  an officially supported feature of this package, we don't run any CI against
  anything but minio and I don't want that maintenance burden.

**Comment by thomasf** [comment]
I made an error above, there only needs to be a single **django-settings-based** region
setting, not one for each storage class. `MINIO_STORAGE_REGION` is enough.

**Comment by ArchiFleKs** [comment]
thanks for you answer i'll look into it, I have another unrelated question, I have no issue uploading a file but when I want to get a file back I get a `message": "[Errno 2] No such file or directory: '/5e26ba44-7989-4140-81b2-cb086bbe577c/bcf-chat.png'"` for example and I've tried every possible URL. 

It is not my app but I can find out more.

**Comment by bat79a** [comment]
Hi !
ArchiFleks was talking about my app.
This is a django rest app and I try to return an ImageField from this url : GET : /projects/1/bitmap

Here is my code : 
```python
        image = Image.objects.get(project=project)
        minio_path_image = image.image_file.url
        content_type_file = 'image/png'
        response = StreamingHttpResponse(open(minio_path_image, 'rb'), content_type=content_type_file)

        response['Content-Disposition'] = "attachment; filename=%s" % str(filename)
        response['Content-Length'] = size

        return response
```

image_file is my ImageField field ;p

for the minio_path_image var I have try all url hardcoded without success...

Thx a lot.

**Comment by thomasf** [comment]
it looks like you are trying to open a relative path to a storage object as a local file. Opening the image_file instead of the URL might work, I don't have the exact semantics in my head. 
If you want to open a file in a storage by path you have to import the correct django-minio storage class and do something like this:  https://docs.djangoproject.com/en/2.0/topics/files/#storage-objects

**Comment by thomasf** [comment]
Also, you can expose minio to end users instead of fetching and serving the file again in django if all that you want is to add response headers..
You can generate an URL with expiration date and response headers if you fetch the minio client from the storage class:  
https://docs.minio.io/docs/python-client-api-reference#presigned_get_object

The url-function of the storage class generates urls: 
https://github.com/py-pa/django-minio-storage/blob/a8926ce011d93e4d08a6405a837485cb8a2fafc7/minio_storage/storage.py#L151

**Comment by bat79a** [comment]
I think that the second option will generate to much link.

And for the first one, import storage i'm not sure how to do that : 
```
from minio_storage import storage

def get(self, request, *args, **kwargs):
        image = Image.objects.get(project=project)
        filename = image.image_file
        size = filename.size

        # The good method that i have to call is open  ?
        image_file = storage.Storage.open() ?
```

Thx a lot.

**Comment by thomasf** [comment]
You have to instantiate the class.

```py
from minio_storage.storage import MinioMediaStorage, MinioStaticStorage

media_storage = MinioMediaStorage()
static_storage = MinioStaticStorage()

static_storage.open("/path/to/file/in/bucket")
```

I still think that you can do it directly from the django model instance field as well but you have to find out how yourself. The django documentation should have something how to open those.  It's the correct solution since you have an model instance loaded from the database already.. Maybe look at the FileField docs.

**Comment by sloanahrens** [comment]
This issue--only being able to use it in us-east-1--made django-minio-storage unusable for me, even though I liked using it with Django and S3 for my us-east-1 cluster. If I only had to run my app in us-east-1 I would continue using this repo, but I need a setup that works for other regions too, and I don't want to have to build and maintain a custom version of this repo just to be able to use other S3 regions. So I just had to go back to using good ole django-storages. Sadness.
