### ISSUE TITLE
Disable SSL verification for self signed certs

### ISSUE THREAD

**Issue by asm582** [py-pa/django-minio-storage#86]
can you please tell how to disable SSL verification for self-signed certs for an Django app running inside a docker container?

**Comment by thomasf** [comment]
why not try installing the certificate instead? You can probably just bind mount it into the container as a volume

**Comment by asm582** [comment]
when I try to use self signed certificate urllib3 library tries to verify it by default, so on my localsetup with ssl enable django app is unable to connect to local minio instance, thats the reason I was asking for a away to disable SSL verfication but still have the ability to use self signed certificates.

**Comment by asm582** [comment]
@thomasf can you please suggest how can I run self-signed certificates with the library?

**Comment by thomasf** [comment]
You can probably configure your own urllib3 instance for the minio client to do wahtever you want. 

That is instead of just using MinioMediaStorage ( https://github.com/py-pa/django-minio-storage/blob/master/minio_storage/storage.py#L318 ) you create your own MinioStorage subclass and instantiate the minio client yourself so that you can assign the urllib pool manager (http_client argument here https://github.com/minio/minio-py/blob/7e03475e9e22915ed4dbcaf5daa6f73dccde1604/docs/API.md#1-constructor )

IIRC you can either remove certificate verification or install your own certificate to this specific http client pool so it won't make other requests less secure if you choose to deactivate it.

https://urllib3.readthedocs.io/en/latest/advanced-usage.html#custom-ssl-certificates
